/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.projecteuler

import kotlin.test.Test
import kotlin.test.assertEquals

class KotlinSolutionsTest {
    @Test fun test001() = assertEquals ("233168",   euler001())
    @Test fun test002() = assertEquals ("4613732",  euler002())
    //    @Test fun test003() = assertEquals ("???",  euler003())
    @Test fun test004() = assertEquals ("906609",  euler004())
    //    @Test fun test005() = assertEquals ("???",  euler005())
    @Test fun test006() = assertEquals ("25164150",  euler006())
    @Test fun test009() = assertEquals ("31875000",  euler009())

}
